// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzpkzqgwtbhoxbkkuvpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cGt6cWd3dGJob3hia2t1dnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDY5MzgsImV4cCI6MjA2NzI4MjkzOH0.ULtlGjH3qxBsTxNlnk3dfW_5ddj_3oCdvzME9LDa45o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});